<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jasa Iklan Meta - Dapatkan Lead Berkualitas</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <style>
        body {
            background-color: #f8f9fa; /* Latar belakang abu-abu sangat muda */
        }
        
        /* Memberi "napas" lebih antar bagian */
        .section-padding {
            padding-top: 5rem;
            padding-bottom: 5rem;
        }

        /* 1. HERO MAKEOVER */
        .hero {
            position: relative;
            background-image: url('https://via.placeholder.com/1600x900.png?text=Professional+Workspace'); /* Ganti dengan gambar Anda */
            background-size: cover;
            background-position: center;
            background-attachment: fixed; /* Efek parallax */
        }
        .hero::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)); /* Overlay gelap */
        }
        .hero .container {
            position: relative;
            z-index: 2;
        }

        /* 2. PROBLEM CARDS */
        .problem-card {
            border: 0;
            border-left: 5px solid var(--bs-danger);
            transition: transform 0.2s ease-in-out;
        }
        .problem-card:hover {
            transform: translateY(-5px);
        }

        /* 3. STAT CARDS (Pengganti Tabel) */
        .stat-card {
            text-align: center;
            padding: 1.5rem;
            border-radius: 0.5rem;
            background-color: #fff;
            box-shadow: 0 0.125rem 0.25rem rgba(0,0,0,.075);
        }
        .stat-card .stat-number {
            font-size: 2.5rem;
            font-weight: 700;
        }
        .stat-card .stat-label {
            font-size: 1rem;
            text-transform: uppercase;
            color: var(--bs-secondary);
        }
        .stat-before {
            color: var(--bs-danger);
            text-decoration: line-through;
            opacity: 0.7;
        }
        .stat-after {
            color: var(--bs-success);
        }

        /* 4. PRICE CARD */
        .price-card {
            transition: transform 0.2s ease-in-out, box-shadow 0.2s;
        }
        .price-card:hover {
            transform: scale(1.02);
            box-shadow: 0 1rem 3rem rgba(0,0,0,.175)!important;
        }
        
        /* Ganti link WA Anda di sini */
        .cta-button {
            --wa-link: "https://api.whatsapp.com/send?phone=628123456789&text=Halo%2C%20saya%20tertarik%20dengan%20jasa%20iklan%20Meta%20untuk%20lead%20berkualitas.";
        }
        .btn-wa {
             background-color: #25D366;
             border-color: #25D366;
             color: white;
        }
        .btn-wa:hover {
            background-color: #1EAE50;
            border-color: #1EAE50;
            color: white;
        }

    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top shadow-sm">
        <div class="container">
            <a class="navbar-brand fw-bold" href="#">[Nama Bisnis Anda]</a>
        </div>
    </nav>

    <header id="hero" class="hero section-padding text-white text-center">
        <div class="container">
            <h1 class="display-4 fw-bold">Fokus Closing Saja. Biar Kami yang Kirim Calon Klien Berkualitas ke WhatsApp Anda.</h1>
            <p class="lead my-4">Berhenti membuang waktu produktif Anda meladeni prospek 'iseng' & 'PHP' dari iklan Facebook & Instagram.</p>
            <a href="var(--wa-link)" class="btn btn-wa btn-lg fw-bold px-5 cta-button">
                <i class="bi bi-whatsapp me-2"></i>Konsultasi Gratis & Cek Slot
            </a>
        </div>
    </header>

    <section id="problem" class="section-padding">
        <div class="container">
            <h2 class="fw-bold mb-5 text-center">Anda Tidak Butuh 100 Chat, <br>Anda Butuh 10 Closing.</h2>
            <p class="lead text-center mb-5">Sebagai Agen Jasa (Properti, Asuransi, Travel), waktu Anda adalah aset paling berharga. Tapi seringkali waktu itu habis untuk:</p>
            
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card shadow-sm h-100 problem-card">
                        <div class="card-body p-4">
                            <i class="bi bi-x-circle-fill fs-1 text-danger mb-3"></i>
                            <h5 class="fw-bold">Meladeni Chat "Iseng"</h5>
                            <p>Menjawab pertanyaan "Info dong" atau "Harganya berapa?" dari orang yang jelas tidak punya niat beli (lalu menghilang).</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card shadow-sm h-100 problem-card">
                        <div class="card-body p-4">
                            <i class="bi bi-person-x-fill fs-1 text-danger mb-3"></i>
                            <h5 class="fw-bold">Prospek Tidak Qualified</h5>
                            <p>Menghabiskan jam-jam berharga me-follow up orang yang jelas-jelas tidak *qualified* (tidak punya budget atau hanya iseng).</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card shadow-sm h-100 problem-card">
                        <div class="card-body p-4">
                            <i class="bi bi-calendar-x fs-1 text-danger mb-3"></i>
                            <h5 class="fw-bold">Target Komisi Terlewat</h5>
                            <p>Bukan karena Anda tidak jago jualan, tapi karena waktu Anda habis untuk menyaring prospek sampah.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="solution" class="section-padding bg-white">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 order-lg-2 mb-4 mb-lg-0">
                    <img src="https://via.placeholder.com/500x400.png?text=Diagram+Sistem+Penyaringan" alt="Sistem Penyaringan" class="img-fluid rounded shadow">
                </div>
                <div class="col-lg-6 order-lg-1">
                    <h2 class="fw-bold mb-4">Solusi Kami: Iklan Meta (FB/IG) dengan *Sistem Penyaringan Prospek*.</h2>
                    <p class="lead">Kami bukan sekadar 'pasang iklan'. Kami merancang *copywriting* dan *targeting* yang secara sengaja **menyaring** audiens di awal.</p>
                    <p>Iklan "biasa" dirancang untuk mendapat *klik* sebanyak-banyaknya. Iklan kami dirancang untuk *menolak* orang yang tidak serius.</p>
                    <ul class="list-unstyled fs-5 mt-4">
                        <li class="mb-3 d-flex">
                            <i class="bi bi-check-circle-fill text-success me-3 mt-1"></i>
                            <div><strong>Menyingkirkan Prospek 'Iseng'</strong><br>Copywriting kami membuat mereka sadar diri *sebelum* meng-klik iklan.</div>
                        </li>
                        <li class="mb-3 d-flex">
                            <i class="bi bi-check-circle-fill text-success me-3 mt-1"></i>
                            <div><strong>Menarik Prospek 'Serius'</strong><br>Kami fokus pada audiens yang punya *masalah nyata* dan *kemampuan finansial*.</div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="process" class="section-padding">
        <div class="container text-center">
            <h2 class="fw-bold mb-5">Proses Kerja Kami yang Transparan</h2>
            <div class="row">
                <div class="col-md-3 mb-4">
                    <div class="card h-100 shadow-sm border-0">
                        <div class="card-body p-4">
                            <span class="display-3 fw-bold text-primary">1</span>
                            <h4 class="fw-bold mt-3">Riset & Strategi</h4>
                            <p>Kami bedah *psikografi* (keraguan & masalah) klien ideal Anda.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-4">
                    <div class="card h-100 shadow-sm border-0">
                        <div class="card-body p-4">
                            <span class="display-3 fw-bold text-primary">2</span>
                            <h4 class="fw-bold mt-3">Setup Iklan Penyaring</h4>
                            <p>Pembuatan copywriting dan visual yang fokus pada *edukasi*.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-4">
                    <div class="card h-100 shadow-sm border-0">
                        <div class="card-body p-4">
                            <span class="display-3 fw-bold text-primary">3</span>
                            <h4 class="fw-bold mt-3">Optimasi Harian</h4>
                            <p>Anggaran iklan dialihkan setiap hari ke iklan yang paling efektif.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-4">
                    <div class="card h-100 shadow-sm border-0">
                        <div class="card-body p-4">
                            <span class="display-3 fw-bold text-primary">4</span>
                            <h4 class="fw-bold mt-3">Laporan H+1</h4>
                            <p>Anda mendapat laporan progres dan biaya harian. 100% transparan.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section id="proof" class="section-padding bg-white">
        <div class="container">
            <h2 class="fw-bold text-center mb-5">Jangan Percaya Kata Kami. Percaya Hasil Efisiensi Mereka.</h2>
            
            <div class="row g-4 align-items-stretch">
                <div class="col-lg-6 mb-4 mb-lg-0">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body p-5">
                            <i class="bi bi-quote fs-1 text-primary"></i>
                            <blockquote class="blockquote fs-5 mb-0 mt-3">
                                <p>"Saya hampir menyerah pasang iklan di Meta. 99% cuma 'Info dong'. Waktu saya habis. Setelah ditangani [Nama Anda], copywriting iklannya diubah jadi 'menusuk'. Chat anjlok dari 50/minggu jadi 10-an. Tapi dari 10 chat itu, 8 di antaranya *serius* survei lokasi. Bulan lalu **closing 2 unit rumah**..."</p>
                                <footer class="blockquote-footer mt-3 fs-6">Rian H. <cite title="Source Title">Agen Properti Independen</cite></footer>
                            </blockquote>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-6">
                    <h5 class="fw-bold text-center mb-4">Studi Kasus: Agen Travel (Sebelum vs Sesudah)</h5>
                    <div class="row g-3">
                        <div class="col-6">
                            <div class="stat-card">
                                <div class="stat-number stat-before">214</div>
                                <div class="stat-label">Total Chat (Sebelum)</div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="stat-card">
                                <div class="stat-number stat-after">31</div>
                                <div class="stat-label">Total Chat (Sesudah)</div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="stat-card">
                                <div class="stat-number stat-before">1</div>
                                <div class="stat-label">Closing (Sebelum)</div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="stat-card">
                                <div class="stat-number stat-after">4</div>
                                <div class="stat-label">Closing (Sesudah)</div>
                            </div>
                        </div>
                    </div>
                    <p class="text-center text-muted mt-4">Anggaran iklan sama (Rp 3 Juta). Bedanya? Waktu Anda jauh lebih efisien dan profit meningkat.</p>
                </div>
            </div>
        </div>
    </section>

    <section id="offer" class="section-padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="card shadow-lg text-center price-card border-0">
                        
                        <div class="card-header bg-primary text-white p-4">
                            <h2 class="fw-bold mb-0">Investasi Anda untuk Waktu yang Produktif</h2>
                        </div>
                        
                        <div class="card-body p-5">
                            <h5 class="card-title text-muted">Jasa Setup & Optimasi Iklan</h5>
                            <p class="display-4 fw-bold text-primary my-3">Rp 1.800.000</p>
                            <p class="fs-5 mb-4">/ Bulan</p>
                            <p class="text-muted small">(Termasuk: Riset, Copywriting, Desain Iklan, Optimasi Harian, & Laporan H+1).</p>
                        </div>
                        
                        <div class="card-footer p-4 bg-light border-0">
                            <h5 class="fw-bold">Garansi Kualitas Proses Kami</h5>
                            <p class="mb-0">Cukup bayar DP 60% untuk memulai. Sisa 40% (pelunasan) hanya Anda bayarkan di akhir bulan **jika Anda puas dengan kualitas proses kerja dan transparansi laporan kami.**</Jp>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="cta" class="section-padding bg-white text-center">
        <div class="container">
            <h2 class="display-5 fw-bold">Siap Berhenti Meladeni Prospek Iseng?</h2>
            <p class="lead my-4 text-muted">Slot terbatas. Kami hanya mengambil 5 klien baru per bulan untuk menjaga kualitas layanan.</p>
            <a href="var(--wa-link)" class="btn btn-wa btn-lg fw-bold px-5 py-3 cta-button">
                <i class="bi bi-whatsapp me-2"></i>Ya, Saya Mau Konsultasi Gratis Sekarang!
            </a>
        </div>
    </section>

    <footer class="py-4 text-center">
        <div class="container">
            <p class="mb-0 text-muted">&copy; 2025 [Nama Bisnis Anda]. All rights reserved.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>